Abstract and Encapulasion

In [1]:
import numpy as np 
a=np.array([1,2,3,400])
a

array([  1,   2,   3, 400])

In [23]:
import numpy as np
a=np.zeros((5,5))
a[0:2,0:-2]=1
a

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
a=np.array([[1,2,3],[1,2,3]])
a.reshape(3,2)

array([[1, 2],
       [3, 1],
       [2, 3]])

In [6]:
a=np.array([[[1,2,3],[1,2,3]]])
a.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [1]],

       [[2],
        [3]]])

In [7]:
a=np.array([1,1+2j])
b=np.real(a)
c=np.imag(a)
print(b)
c

[1. 1.]


array([0., 2.])

In [10]:
a=np.random.random((5,3))
b=np.random.random((3,2))


array([[0.68840164, 0.26147016],
       [0.69274171, 0.62083851],
       [1.60656062, 0.87055999],
       [0.6200642 , 0.3518146 ],
       [0.96368196, 0.5186845 ]])

In [25]:
a=np.array([1,0,3])
c=np.array([1,2,3])
b=np.intersect1d(a,c)
b

array([1, 3])